I18n es
uom-assistant/uom-assistant pull request #2
Opened 2021-07-20 09:28 UTC by Gnefil

i18n: src/components Spanish translation completed

2021-07-21 02:05 UTC, yrccondor requested changes

2021-07-21 02:05 UTC, yrccondor commented on src/components/subjects.vue
> +        "link_format": "URL[nombre][contraseña]",
missing spaces after every left brackets

2021-07-21 02:05 UTC, yrccondor commented on src/components/clock.vue
> +        "Kiritimati": "Kiritimati"
Could you please remove all country/city names if they are as same as English?

2021-07-21 10:07 UTC, Gnefil commented
The requested changes are done, although countries and cities may take a while, we can place them in another pull request.

2021-07-21 10:42 UTC, Gnefil commented
Changed self study in Spanish into shorter word

2021-07-24 14:59 UTC, yrccondor requested changes

2021-07-24 14:59 UTC, yrccondor commented on src/components/clock.vue
> +        "Wallis and Futuna": "Wallis y Futuna",
the extra ending comma leads to build failure

2021-07-24 14:59 UTC, yrccondor commented on src/components/calendar.vue
> +        "self_study": " (Autoestudio) "
no space is needed **in the end**

2021-07-24 14:59 UTC, yrccondor commented on src/components/settings.vue
> +        "where_ica_body": "Vaya a <a href=\"https://timetables.manchester.ac.uk/\" target=\"_blank\" rel=\"noreferrer noopener\">, esta página</a>，y tras iniciar sesión haga clic en el botón de \"Sub
a comma within the a element and a full-width comma after the a element

2021-07-24 19:06 UTC, yrccondor approved these changes
Cool, good job!

2021-07-24 19:09 UTC, yrccondor commented
build faild again, re-check needed

2021-07-25 05:13 UTC, yrccondor approved these changes
great, we can merge now

2021-07-25 05:20 UTC, merged